### ISSUE TITLE
Configuration?

### ISSUE THREAD

**Issue by till** [robertdebock/ansible-role-fail2ban#2]
**Describe the bug**
It seems the role doesn't configure anything. Is it a WIP?

It installs fail2ban and enables the service.

**Comment by robertdebock** [comment]
Hi @till, you are right, looking at [some page about configuration](https://www.linode.com/docs/security/using-fail2ban-for-security/#configure-fail2ban-local) there are quite a few things you may want to change.

Can you help me by telling me what things you would like to be able to configure?

**Comment by till** [comment]
@robertdebock I am not sure if it makes sense to duplicate efforts?

Found this on Galaxy and started using it:
https://github.com/nbigot/ansible-fail2ban

E.g., custom jails, all time settings, etc.. But again, I am not sure if it's not too much work since there is a role already. :)

**Comment by robertdebock** [comment]
Great, thanks for the reference, I'll see what I can do.

The main purpose of the roles I write is to work on many distributions, that could be an added benefit.

Anyway, thanks, I'll look into it!

**Comment by robertdebock** [comment]
I've introduced a set of settings and default values. When [the build](https://travis-ci.org/robertdebock/ansible-role-fail2ban/builds/495821291) is done, I'll release.

Thanks for you feedback @till

**Comment by robertdebock** [comment]
Fixed with the latest release.
