### ISSUE TITLE
Custom configuration in .local file instead of jail.conf

### ISSUE THREAD

**Issue by rohankrishnadev** [robertdebock/ansible-role-fail2ban#4]
**Is your feature request related to a problem? Please describe.**
This role modifies the jail.conf file for customisation. This file gets overwritten with every update.

**Describe the solution you'd like**
According to [fail2ban](https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf) the recommended approach would be to provide customisations in jail.local or jail.d/customisation.local file. Switching jail.conf to jail.local in [main.yml](https://github.com/robertdebock/ansible-role-fail2ban/blob/b03d092ba53c7f8797f6d70e67f194ff7be07011/tasks/main.yml#L25) should do the trick.

**Describe alternatives you've considered**
It might be worth considering putting in a template customisation.local file with sane defaults which the user can switch with their own. This could be done by [playbook pathing](https://docs.ansible.com/ansible/latest/user_guide/playbook_pathing.html). The file name could be provided in a variable, that way the user won't have to modify the role. 

**Additional context**
N/A

**Comment by robertdebock** [comment]
Sorry, I did not see your issue until today. Good suggestion, I'll work on it!

**Comment by robertdebock** [comment]
Need to test and release. Closing when done, could take an hour or two.

**Comment by robertdebock** [comment]
That was quicker than expected, the tests were successful and release to galaxy has been done, version 3.0.0.

Thanks @rohankrishnadev for your help!
